// Homework2/yvekaria/src/components/ScatterPlot.vue
<template>
  <div id="scatter-plot"></div>
</template>

<script>
import * as d3 from 'd3';

export default {
  mounted() {
    // Fetch and parse the CSV file
    d3.csv('../../data/pokemon_alopez247.csv').then(data => {
      // Process and retain only necessary columns
      data = data.map(d => ({
        Weight_kg: +d.Weight_kg,
        Height_cm: +d.Height_m * 100,
        Body_Style: d.Body_Style,
        Catch_Rate: +d.Catch_Rate
      }));

      // Your D3.js code to create the scatter plot using processed data
      const margin = { top: 2, right: 20, bottom: 50, left: 50 };
      const width = 1450 // 1100 - margin.left - margin.right;
      const height = 240 - margin.top - margin.bottom;

      const svg = d3
        .select('#scatter-plot')
        .append('svg')
        .attr('width', width + margin.left + margin.right)
        .attr('height', height + margin.top + margin.bottom)
        .append('g')
        .attr('transform', `translate(${margin.left},${margin.top})`);

      // X-axis scale (log scale for Height_cm)
      const xScale = d3
        .scaleLog()
        .domain([9, d3.max(data, d => d.Height_cm)])
        .range([0, width-300]);

      // Y-axis scale (log scale for Weight_kg)
      const yScale = d3
        .scaleLog()
        .domain([0.1, d3.max(data, d => d.Weight_kg)])
        .range([height, 0]);

      // Scale for circle size based on Catch_Rate
      const sizeScale = d3
        .scaleLinear()
        .domain([0, d3.max(data, d => d.Catch_Rate)])
        .range([1.5, 16.5]);

      // Color scale for Body_Style
      const colorScale = d3
        .scaleOrdinal(d3.schemeCategory10)
        .domain(data.map(d => d.Body_Style));

      // Draw circles
      svg.selectAll('circle')
        .data(data)
        .enter()
        .append('circle')
        .attr('cx', d => xScale(d.Height_cm))
        .attr('cy', d => yScale(d.Weight_kg))
        .attr('r', d => sizeScale(0.5 * d.Catch_Rate))
        .attr('fill', d => colorScale(d.Body_Style));

      // X-axis
      svg.append('g')
        .attr('transform', `translate(0,${height})`)
        .call(d3.axisBottom(xScale).ticks(5, '.0s'))
        .selectAll('text')
        .style('font-size', '14px');
      
      svg.append('text')
        .attr('x', (width - 275) / 2)
        .attr('y', height + margin.bottom - 5)
        .attr('fill', '#000')
        .attr('text-anchor', 'middle')
        .style('font-size', '16px')
        .text('Height (cm) (logscale)');

      // Y-axis
      svg.append('g')
        .call(d3.axisLeft(yScale).ticks(5, '.0s'))
        .selectAll('text')
        .style('font-size', '14px');
        
      svg.append('text')
        .attr('x', -(height / 2))
        .attr('y', -margin.left + 10)
        .attr('fill', '#000')
        .attr('text-anchor', 'middle')
        .attr('transform', 'rotate(-90)')
        .style('font-size', '16px')
        .text('Weight (kg) (logscale)');

      // Legend
      const legend = svg.append('g')
        .attr('class', 'legend')
        //.attr('transform', 'translate(${width + 200}, 0)');

      const legendKeys = Array.from(new Set(data.map(d => d.Body_Style)));
      legend.selectAll('rect')
        .data(legendKeys)
        .enter()
        .append('rect')
        .attr('x', width - 275)
        .attr('y', (d, i) => i * 17)
        .attr('width', 15)
        .attr('height', 15)
        .attr('fill', d => colorScale(d));

      legend.selectAll('text')
        .data(legendKeys)
        .enter()
        .append('text')
        .attr('x', width - 250)
        .attr('y', (d, i) => i * 17 + 12.5)
        .text(d => d.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()));

      // Add capture rate description
      svg.append('text')
        .attr('x', 85) // Set x-coordinate for the center of the plot
        .attr('y', -height + 420) // Set y-coordinate for the top of the plot
        .attr('text-anchor', 'middle')
        .style('font-size', '18px')
        .style('font-weight', 'bold')
        .text('Pokemon Physique Distribution');

      // Title
      svg.append('text')
        .attr('x', 175) // Set x-coordinate for the center of the plot
        .attr('y', -height + 200) // Set y-coordinate for the top of the plot
        .attr('text-anchor', 'middle')
        .style('font-size', '14px')
        .text('Size represents the scaled Pokemon Capture Rate');
    });
  }
};
</script>

<style scoped>
/* Add your component-specific styles here */
</style>

// Homework2/mvenkat/src/Components/ScatterPlot.jsx
import React, { useRef, useEffect } from "react";
import * as d3 from "d3";
import "../App.css";

const ScatterPlot = ({ data }) => {
  const ref = useRef();

  useEffect(() => {
    const svg = d3.select(ref.current);
    svg.selectAll("*").remove(); // Clear SVG

    const margin = { top: 10, right: 200, bottom: 200, left: 0 };
    const width = 600 - margin.left - margin.right;
    const height = 450 - margin.top - margin.bottom;

    // Appends a group element to the SVG
    const mainGroup = svg
      .append("g")
      .attr("transform", `translate(${margin.left + 50},${margin.top})`);

    // X scale and axis
    const xScale = d3
      .scaleBand()
      .domain(data.map((d) => d["Fav genre"]))
      .range([0, width])
      .padding(0.2);

    mainGroup
      .append("g")
      .attr("transform", `translate(0,${height})`)
      .call(d3.axisBottom(xScale))
      .selectAll("text")
      .attr("transform", "rotate(-45)")
      .style("text-anchor", "end");

    mainGroup
      .append("text")
      .attr("class", "x label")
      .attr("text-anchor", "middle")
      .attr("x", width / 2)
      .attr("y", height + 70) // You can adjust this value for positioning
      .text("Favorite genre")
      .attr("fill", "white")
      .style("font-size", "12px");

    // Y scale and axis
    const yScale = d3
      .scaleLinear()
      .domain([0, d3.max(data, (d) => +d.Age)])
      .range([height, 0]);

    mainGroup.append("g").call(d3.axisLeft(yScale));

    mainGroup
      .append("text")
      .attr("class", "y label")
      .attr("text-anchor", "middle")
      .attr("y", -50) // You can adjust this value for positioning
      .attr("x", -height / 2)
      .attr("dy", ".75em")
      .attr("transform", "rotate(-90)")
      .text("Age")
      .attr("fill", "white")
      .style("font-size", "12px");

    // Color palette based on 'Music effects'
    const colorScale = d3
      .scaleOrdinal()
      .domain(["Improve", "No effect", "Worsen"])
      .range(["green", "blue", "red"]);

    // Create the scatter plot
    mainGroup
      .selectAll("dot")
      .data(data)
      .enter()
      .append("circle")
      .attr("cx", (d) => xScale(d["Fav genre"]) + xScale.bandwidth() / 2)
      .attr("cy", (d) => yScale(d.Age))
      .attr("r", 2.5)
      .style("fill", (d) => colorScale(d["Music effects"]))
      .style("opacity", 0.8);

    // Legend
    const legend = mainGroup
      .append("g")
      .attr("transform", `translate(${width + 30},10)`);

    colorScale.domain().forEach((value, index) => {
      const legendRow = legend
        .append("g")
        .attr("transform", `translate(0,${index * 20})`);

      // legendRow
      //   .append("rect")
      //   .attr("width", 10)
      //   .attr("height", 10)
      //   .attr("fill", colorScale(value));

      legendRow
        .append("circle")
        .attr("cx", 5) // Half of the previous width/height (10/2)
        .attr("cy", 5) // Half of the previous width/height (10/2)
        .attr("r", 5) // Radius of the circle
        .attr("fill", colorScale(value));

      legendRow
        .append("text")
        .attr("x", -10)
        .attr("y", 10)
        .attr("font-family", "Arial")
        .attr("font-size", 10)
        .attr("text-anchor", "end")
        .style("text-transform", "capitalize")
        .attr("fill", "white")
        .text(value);
    });
  }, [data]);

  return (
    <div className="scatterContainer">
      <p style={{ color: "#ACACAC", fontSize: 18, fontFamily: "serif" }}>
        Favorite Music Genre across Ages
        <br />
        <span style={{ color: "grey", fontSize: 14, fontFamily: "serif" }}>
          {" "}
          Along with Effects on Mental Health
        </span>
      </p>
      <svg width="500" height="350" ref={ref}></svg>
    </div>
  );
};

export default ScatterPlot;
